let siswa = prompt("Nama siswa:");
let nilai = parseInt(prompt("Nilai 0-100:"));
let grade;
if (nilai >= 90) grade = "A";
else if (nilai >= 80) grade = "B";
else if (nilai >= 70) grade = "C";
else if (nilai >= 60) grade = "D";
else grade = "E";
console.log("Siswa: " + siswa);
console.log("Grade: " + grade);